version: '3'

services:
  clickhouse-connector:
    image: "epam/timebase-clickhouse-connector:${CONNECTOR_VERSION}"
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g -Dspring.config.additional-location=/opt/deltix/timebase/clickhouse-connector/application.yaml
    depends_on:      
      clickhouse:
        condition: service_healthy
    volumes:
      - "./clickhouse-connector/application.yaml:/opt/deltix/timebase/clickhouse-connector/application.yaml:ro"    

  timebase:
    image: "finos/timebase-ce-server:${TIMEBASE_VERSION}"
    ports:
      - 8011:8011
    environment:
      - JAVA_OPTS=
        -DTimeBase.metrics.enable=true
        -Xms4g
        -Xmx4g
    entrypoint: [ "/timebase-server/bin/tdbserver.sh", "$${JAVA_OPTS}", "-tb", "-home", "/timebase-home" ]
    stop_grace_period: 1m
    volumes:
      - "./timebase-home:/timebase-home"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8011/tb/ping || exit 1

  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - ./clickhouse-home/config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-home/config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-home/config/docker.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
      - ./clickhouse-home/logs/:/var/log/clickhouse-server/
#      - ./clickhouse-home/data/:/var/lib/clickhouse/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1    